import type { Metadata } from "next";
import { Quicksand, } from "next/font/google";
import "./globals.css";

const geistSans = Quicksand({
  variable: "--font-quicksand-sans",
  subsets: ["latin"],
});

const geistMono = Quicksand({
  variable: "--font-quicksand-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
